### ISSUE TITLE
some issues about eight simple but typical approaches (E1)

### ISSUE THREAD

**Issue by Anonymous034** [bytedance/E3PO#41]
根据：[README.md](https://github.com/bytedance/E3PO/blob/main/README.md)
我验证了custom_eac方法，并发现现在好像只有 custom_eac 是完整的

仓库介绍了8种方案
在里面介绍了有E1方法的介绍
[BasicTutorial.md](https://github.com/bytedance/E3PO/blob/main/docs/BasicTutorial.md)
但是我未能发现相关文件
![image](https://github.com/bytedance/E3PO/assets/110434246/b8d3413e-e198-467a-b753-317702d8f566)

请问这个仓库是不是后续还要更新新的方案呢？我们想在这个平台上验证我们的FOV自适应算法

**Comment by bytedance-e3po** [comment]
Hi,
In the current version, the name of E1 has been updated to "erp". Therefore, the correct process, similar to [Run scripts](https://github.com/bytedance/E3PO/blob/main/README.md#run-scripts), is as follows:

python ./e3po/make_preprocessing.py -opt approaches/erp/erp.yml
python ./e3po/make_decision.py -opt approaches/erp/erp.yml
python ./e3po/make_evaluation.py -opt approaches/erp/erp.yml

We have updated the description in [BasicTutorial.md](https://github.com/bytedance/E3PO/blob/main/docs/BasicTutorial.md). Thank you very much for your feedback!

**Comment by bytedance-e3po** [comment]
If you have any further inquiries, you can join the [topic group](https://github.com/bytedance/E3PO/blob/main/mmsys24gc/mmsys24gc_group.jpeg) for discussion as quickly as possible.

**Comment by Anonymous034** [comment]
Thanks!
